name: Flutter Android Build

on:
  push:
    branches: [ "build-app/android" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy mã nguồn
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Cài Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"

      # 3. Cài dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Tạo lại file firebase_options.dart từ GitHub Secrets
      - name: Create firebase_options.dart
        run: echo "$FIREBASE_OPTIONS" > lib/firebase_options.dart
        env:
         FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}

      # 5. Phân tích code (hiển thị warning nhưng ko dừng)
      - name: Analyze project source
        run: flutter analyze || true

      # 6. Chạy test (optional)
      - name: Run tests
        run: flutter test

      - name: Run tests and show pass percentage
        run: |
          flutter test --machine > test_output.json
          passed=$(grep -c '"result":"success"' test_output.json || true)
          failed=$(grep -c '"result":"failure"' test_output.json || true)
          total=$((passed + failed))
          if [ "$total" -gt 0 ]; then
            percent=$((100 * passed / total))
            echo "----- Passed: $passed / $total tests ($percent%)"
          else
            echo "xxxxx No tests found."
          fi

      # 7. Build file APK (release)
      - name: Build Android APK
        run: flutter build apk --release --dart-define=BASE_URL=${{ secrets.PROD_BASE_URL }}

      # 8. Lưu file APK ra artifacts để tải về
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # -----------------------
      # Firebase App Distribution
      # -----------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 1. Tạo file service-account.json từ GitHub Secret
      - name: Create firebase service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

      # 2. Upload APK
      - name: Distribute APK via Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} \
            --groups "testers" \
            --release-notes "Automated build"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json